/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArtRouteImport } from './routes/art'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as PoetRouteImport } from './routes/poet'
import { Route as SocialWorkerRouteImport } from './routes/social-worker'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetRoute = PoetRouteImport.update({
  id: '/poet',
  path: '/poet',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialWorkerRoute = SocialWorkerRouteImport.update({
  id: '/social-worker',
  path: '/social-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/author': typeof AuthorRoute
  '/connect': typeof ConnectRoute
  '/poet': typeof PoetRoute
  '/social-worker': typeof SocialWorkerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/author': typeof AuthorRoute
  '/connect': typeof ConnectRoute
  '/poet': typeof PoetRoute
  '/social-worker': typeof SocialWorkerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/author': typeof AuthorRoute
  '/connect': typeof ConnectRoute
  '/poet': typeof PoetRoute
  '/social-worker': typeof SocialWorkerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/art'
    | '/author'
    | '/connect'
    | '/poet'
    | '/social-worker'
    | '/admin/dashboard'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/art'
    | '/author'
    | '/connect'
    | '/poet'
    | '/social-worker'
    | '/admin/dashboard'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/art'
    | '/author'
    | '/connect'
    | '/poet'
    | '/social-worker'
    | '/admin/dashboard'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtRoute: typeof ArtRoute
  AuthorRoute: typeof AuthorRoute
  ConnectRoute: typeof ConnectRoute
  PoetRoute: typeof PoetRoute
  SocialWorkerRoute: typeof SocialWorkerRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poet': {
      id: '/poet'
      path: '/poet'
      fullPath: '/poet'
      preLoaderRoute: typeof PoetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-worker': {
      id: '/social-worker'
      path: '/social-worker'
      fullPath: '/social-worker'
      preLoaderRoute: typeof SocialWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtRoute: ArtRoute,
  AuthorRoute: AuthorRoute,
  ConnectRoute: ConnectRoute,
  PoetRoute: PoetRoute,
  SocialWorkerRoute: SocialWorkerRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
